#### Brute-Force คือ การแก้ปัญหาแบบที่ง่ายที่สุดแต่โดยรวมแล้วมีประสิทธิภาพต่ำ มักใช้ในกรณีที่เราคิดอัลกอริทึมอื่นยังไม่ออก ซึ่งมีหลักการแก้ปัญหาโดยการสั่งให้ทำงานวนไปเรื่อย ๆ จนกว่าจะได้คำตอบ (เป็นการเช็คทุกตัว n ตัว) แต่ไม่เหมาะกับกับข้อมูลที่มีจำนวนมากเพราะจะใช้เวลานาน โดยปัญหาที่สามารถแก้ไขได้ด้วย Brute-Force ได้แก่
1. Bubble Sort คือ จะทำการเปรียบเทียบข้อมูลที่อยู่ติดกันและจะทำการสลับตัวที่น้อยกว่าว่าไว้ด้านหน้า ทำซ้ำจนกว่าทุกตัวจะครบ
2. Selection Sort คือ จะทำการเลือกค่าที่น้อยที่สุดในแต่ละรอบ และดึงออกมาเก็บเรียงไว้
3. String matching คือ การนำคำที่ต้องการหา ไปหาใน String อีกตัวหนึ่ง
4. Closest-pair คือ การหาระยะทางที่สั้นที่สุดระหว่างคู่จุด โดยยังสามารถหาได้จากการใช้ Euclidean นั่นคือ sqrt ของ 
   ((x[i]-x[j])**2) + ((y[i]-y[j]**2)) ซึ่งต้องยกกำลัง 2 เนื่องจากจุดแต่ละจุดอยู่กันคนละระนาบ
5. Convex-Hull Problem คือ รูปนูนหลายเหลี่ยมที่เล็กที่สุดที่ถูก enclose สำหรับ set S of n points ซึ่งแบ่วออกเป็น
   - 5.1 Convex hull คือรูปที่มีมุมป้านทุกมุม
   - 5.2 Concave hull คือรูปมีได้ทั้งมุมป้านและมุมแหลมในทุกมุม

#### Exhaustive Search คือ การค้นหาแบบทั้งหมด โดยสามารถหา solution ได้ 3 steps ได้แก่
1. Generate ทุก ๆ element ของปัญหา
2. เลือกสิ่งที่เราต้องการ ต่อ constraints หรือตัวแปรทั้งหมด
3. หาวิธีการแก้ปัญหาที่เหมาะสม

#### ตัวอย่างปัญหาที่ใช้ Brute-Force
1. Traveling Salesman Problems : ปัญหาการเดินไปให้ครบทุกเมือง โดยห้ามเดินซ้ำและระยะทางสั้นที่สุด สามารถหาจาก Halmiltonian circuit ที่มี length ที่สั้นที่สุดได้ (ไม่เหมือนกับ minimum Spanning Tree เพราะมีการวนกลับมาที่จุดเริ่มต้น)
2. Knapsack Problems : ปัญหาการเลือกตัวเลือกในเงื่อนไขที่จำกัด เพื่อให้ได้ค่าที่เราต้องการให้คุ้มค่าที่สุด
   - 2.1 Generate subset ทั้งหมดที่เป็นไปได้ของ item
   - 2.2 คำนวณน้ำหนักทั้งหมดของ subset ใน knapsack
   - 2.3 หา Subset ที่มี Value มากที่สุด
3. Assignment Problems : ปัญหาการมอบหมายงานที่ว่า How to put the right man on the right job คือต้องการให้เกิดการจัดงานที่ดีที่สุด  
   โดยอาจทำให้เกิดต้นทุนในการดำเนินการที่ต่ำที่สุด หรือทำให้เวลาในการทำงานโดยรวมน้อยที่สุด

#### สรุป Brute-Force และ Exhaustive search เหมาะกับการใช้งานตอนไหน
1. Brute Force สามารถใช้ได้กับปัญหาที่หลากหลาย โดยง่ายต่อการออกแบบและบางครั้งเป็นเพียงวิธีเดียวที่จะสามารถใช้แก้ปัญหาที่ยากได้
2. โจทย์ที่ไม่คุ้มค่ากับเวลาในการที่จะนำมาออกแบบ Efficient algorithm (อัลกอริทึมที่มีประสิทธิภาพที่สุดสำหรับปัญหานั้น) โดยสามารถแก้ปัญหาได้เพียงไม่กี่ปัญหาและมีข้อจำกัดในเรื่องของเวลา
   เนื่องจากบางปัญหาอาจใช้เวลาในการ solve นานเกินไป
3. เหมาะกับปัญหาเล็ก ๆ ที่มี n ไม่มาก ซึ่งเป็นวิธีที่ได้รับการยอมรับว่ามีประสิทธิภาพ
4. เอาไว้ใช้เป็น Benchmark ให้กับ Efficient algorithm อื่น กล่าวคือ เอาไว้เป็นมาตรฐานที่เอาไว้วัดว่าอัลกอริทึมที่เราคิดขึ้นมาดีหรือไม่จากการเทียบว่าเร็วกว่า Time Complexity ที่ Brute-Force ใช้หรือไม่

### Bubble Sort Algorithm

In [3]:
def BubbleSort(receive_list):
    my_list = receive_list
    n = len(my_list)
    for i in range(n-1):
        for j in range(0, n-i-1):
            if my_list[j] > my_list[j+1]:
                my_list[j], my_list[j+1] = my_list[j+1], my_list[j]

    return my_list

In [4]:
#Test case 1 - Bubble Sort
new_list = [12, 15, 9, 21, 19]
sorted_list = BubbleSort(new_list)
print('Sort my_list:', sorted_list)

Sort my_list: [9, 12, 15, 19, 21]


In [5]:
#Test case 2 - Bubble Sort
test_list = [35,25,19,4,13,8,9,12,7,1,3,2]
sorted_list = BubbleSort(test_list)
print('Sort test_list:', sorted_list)


Sort test_list: [1, 2, 3, 4, 7, 8, 9, 12, 13, 19, 25, 35]


### Selection Sort Algorithm

In [10]:
def SelectionSort(receive_list):
    my_list = receive_list
    n = len(my_list)
    for i in range(n-1):
        min_number = i
        for j in range(i+1, n):
            if my_list[j] < my_list[min_number]:
                min_number = j
        my_list[i], my_list[min_number] = my_list[min_number], my_list[i]

    return my_list

In [11]:
#Test case 1 - Selection Sort
new_list = [12, 15, 9, 21, 19]
sorted_list = SelectionSort(new_list)
print('Sort my_list:', sorted_list)

Sort my_list: [9, 12, 15, 19, 21]


In [12]:
#Test case 2 - Selection Sort
new_list = [999,25,35,147,2,1,3,4,5,6,7,8,9,10,11,12,13,14,15]
sorted_list = SelectionSort(new_list)
print('Sort my_list:', sorted_list)

Sort my_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 25, 35, 147, 999]


### String Matching (Brute-Force Algorithm)

In [13]:
def brute_stringmatch(T,P):
    n = len(T)
    m = len(P)
    for i in range(0,n-m):
        j = 0
        while (j < m) and P[j] == T[i+j]:
            j += 1
        if j == m:
            return i
    return -1

In [14]:
#Test Case 1 - String Matching
T = "abracadabra"
P = "ada"
print("String match index:",brute_stringmatch(T,P))

String match index: 5


In [15]:
#Test Case 2 - String Matching
T = "welcome to the jungle"
P = "minecraft"
print("String match index:",brute_stringmatch(T,P))

String match index: -1


### Brute Force Closet Pair Algorithm

In [46]:
import math
def BruteForceClosetPair(x,y):
    n = len(x)
    d = math.inf
    for i in range(n):
        for j in range(i+1,n):
            d = min(d, math.sqrt(((x[i]-x[j])**2) + ((y[i]-y[j])**2)))
    return d

In [47]:
#Test case 1 - Closet Pair
x = [1,2,3]
y = [4,5,6]
print("Distance:",BruteForceClosetPair(x,y))

Distance: 1.4142135623730951


In [48]:
#Test case 2 - Closet Pair
x = [1,1,1,2,2,2,3,3,3]
y = [1,2,3,1,2,3,1,2,3]

print("Distance:",BruteForceClosetPair(x,y))

Distance: 1.0


### Convex-Hull Problem

### Minimum Total Cost (The Assigment Problem)

In [24]:
from itertools import permutations
import time

persons = ["Kanokwan", "Janasporn" , "Napat", "Thanaporn"]
tasks = ["Design algorithm", "Write/debug code", "Analyze complexity", "Do report & presentation"]

cost_matrix = [
    [9, 2, 7, 8],
    [6, 4, 3, 7],
    [5, 8, 1, 8],
    [7, 6, 9, 4]
]

start = time.time()

indexes = list(permutations([0, 1, 2, 3]))

total_list = []
solution_list = []

for times in indexes:
    total = 0

    solution = []

    print("<", end="")
    for number in range(len(times)):
        if number < 3:
            print(cost_matrix[times[number]][number], end=" + ")
        else:
            print(cost_matrix[times[number]][number], end="")
        total += cost_matrix[times[number]][number]

        solution.append(times[number])
        
    print("> =", total)
    total_list.append(total)
    solution_list.append(solution)

end = time.time()

print(end-start)

print("The minimum of hours spent in best solution is", min(total_list), "hours")

min_index = total_list.index(min(total_list))
task_list = solution_list[min_index] 

for task_number, i in enumerate(task_list):
    print("Task", task_number, ":" , tasks[task_number] , "-" , persons[i] )

<9 + 4 + 1 + 4> = 18
<9 + 4 + 9 + 8> = 30
<9 + 8 + 3 + 4> = 24
<9 + 8 + 9 + 7> = 33
<9 + 6 + 3 + 8> = 26
<9 + 6 + 1 + 7> = 23
<6 + 2 + 1 + 4> = 13
<6 + 2 + 9 + 8> = 25
<6 + 8 + 7 + 4> = 25
<6 + 8 + 9 + 8> = 31
<6 + 6 + 7 + 8> = 27
<6 + 6 + 1 + 8> = 21
<5 + 2 + 3 + 4> = 14
<5 + 2 + 9 + 7> = 23
<5 + 4 + 7 + 4> = 20
<5 + 4 + 9 + 8> = 26
<5 + 6 + 7 + 7> = 25
<5 + 6 + 3 + 8> = 22
<7 + 2 + 3 + 8> = 20
<7 + 2 + 1 + 7> = 17
<7 + 4 + 7 + 8> = 26
<7 + 4 + 1 + 8> = 20
<7 + 8 + 7 + 7> = 29
<7 + 8 + 3 + 8> = 26
0.0009982585906982422
The minimum of hours spent in best solution is 13 hours
Task 0 : Design algorithm - Janasporn
Task 1 : Write/debug code - Kanokwan
Task 2 : Analyze complexity - Napat
Task 3 : Do report & presentation - Thanaporn


#### The assignment problem - Hungarian Method

Ref 1 : https://www.youtube.com/watch?v=m23AgUeAJZY
Ref 2 : https://testbook.com/maths/hungarian-method#:~:text=The%20Hungarian%20method%2C%20also%20known,by%20Harold%20Kuhn%20in%201955.
Ref 3 : https://python.plainenglish.io/hungarian-algorithm-introduction-python-implementation-93e7c0890e15

In [5]:
# The assignment problem - Hungarian Method
import numpy as np # Import for visualization
import time 

def hungarian_method(matrix):

    cost_matrix = np.array(matrix)
    # Step 1 : Find the lowest element for each row
    # Subtract that element from each element in the row

    for row in cost_matrix:
        lowest = min(row)
        for index, element in enumerate(row):
            row[index] = element - lowest

    print("Step 1 - Cost Matrix :")
    print(cost_matrix)

    # Step 2 : Find the lowest element for each column
    # Subtract that element from each element in the column
            
    for column in range(len(cost_matrix)):

        # Find the lowest for that column
        lowest = cost_matrix[0][column]

        for row in range(len(cost_matrix)):
            if cost_matrix[row][column] < lowest:
                lowest = cost_matrix[row][column]

        for row in range(len(cost_matrix)):
            cost_matrix[row][column] -= lowest


    print("Step 2 - Cost Matrix :")
    print(cost_matrix)

    # Step 3: Draw lines through the rows and columns that have zeros
    ''' Examine the rows successively until a row with exactly one unmarked zero is found.
        mark this zero with a circle as an assignment will be made there and cross all other zeros in the column.
    '''

    # Step 3: Examine the rows successively until a row with exactly one unmarked zero is found
    # Mark this zero with a circle as an assignment will be made there and cross all other zeros in the column

    # Create a mark_matrix to mark the circle in zeros
    mark_matrix = []
    for row in range(len(cost_matrix)):
        row = []
        for column in range(len(cost_matrix[0])):
            row.append(0)
        mark_matrix.append(row)

    # Iterate through each row
    for row in range(len(cost_matrix)):
        zero_count = 0
        zero_column = -1

        # Count the number of unmarked zeros in the row
        for column in range(len(cost_matrix[0])):
            if cost_matrix[row][column] == 0 and mark_matrix[row][column] == 0:
                zero_count += 1
                zero_column = column

        # If there is exactly one unmarked zero in the row, mark it with a circle
        if zero_count == 1:
            mark_matrix[row][zero_column] = 1

            # Cross all other zeros in the column
            for r in range(len(cost_matrix)):
                if r != row and cost_matrix[r][zero_column] == 0:
                    mark_matrix[r][zero_column] = -1

    '''
    อธิบายเพิ่มเติม Mark Matrix เอาไว้ตรวจสอบว่าเราเลือก 0 ตัวไหนและตัด 0 ตัวไหนออกไป
                0  : ไม่มีการเลือก
                1  : เลือก 0 ที่ช่องนี้
                -1 : ตัด 0 ที่ช่องนี้ออกไป
    '''

    # Step 4: Examine the columns successively until a column with exactly one unmarked zero is found
    # Mark this zero with a circle as an assignment will be made there and cross all other zeros in this row

        # Iterate through each column
    for column in range(len(cost_matrix[0])):
        zero_count = 0
        zero_row = -1

            # Count the number of unmarked zeros in the column
        for row in range(len(cost_matrix)):
            if cost_matrix[row][column] == 0 and mark_matrix[row][column] == 0:
                zero_count += 1
                zero_row = row

        # If there is exactly one unmarked zero in the column, mark it with a circle
        if zero_count == 1:
            mark_matrix[zero_row][column] = 1

            # Cross all other zeros in this row
            for c in range(len(cost_matrix[0])):
                if c != column and cost_matrix[zero_row][c] == 0:
                    mark_matrix[zero_row][c] = -1

    # Print the updated mark_matrix
    print("Updated Mark Matrix:")
    for row in mark_matrix:
        print(row)

    # Step 5 : Check if some row does not have an assignment or marked zero in it
    # The optimal solution has not yet been reached.
        
    optimal_solution = True
    # Iterate through each row
    for row in range(len(cost_matrix)):
        zero_count = 0

        # Count the number of marked zeros in the row
        for column in range(len(cost_matrix[0])):
            if mark_matrix[row][column] == 1:
                zero_count += 1
        else:
            if zero_count == 0:
                optimal_solution = False
                break

    # Step 6 : If the optimal solution has not been reached, go to step 3
    # Draw minimum number of horizontal and vertical lines to cover zeros of the matrix        
    # if not optimal_solution:


    optimal_matrix = []
    for row in range(len(cost_matrix)):
        row = []
        for column in range(len(cost_matrix[0])):
            row.append(0)
        optimal_matrix.append(row)


    # Step 7: Find the rows and columns with the most zeros
    row_zeros = []
    col_zeros = []

    # Count the number of zeros in each row
    for row in range(len(cost_matrix)):
        zero_count = 0
        for column in range(len(cost_matrix[0])):
            if cost_matrix[row][column] == 0:
                zero_count += 1
        row_zeros.append(zero_count)

    # Count the number of zeros in each column
    for column in range(len(cost_matrix[0])):
        zero_count = 0
        for row in range(len(cost_matrix)):
            if cost_matrix[row][column] == 0:
                zero_count += 1
        col_zeros.append(zero_count)

    # print(row_zeros)
    # # Find the row with the most zeros
    # max_row_zeros = max(row_zeros)
    # max_row_index = row_zeros.index(max_row_zeros)

    # # Find the column with the most zeros
    # max_col_zeros = max(col_zeros)
    # max_col_index = col_zeros.index(max_col_zeros)

    # print("Row with the most zeros:", max_row_index)
    # print("Column with the most zeros:", max_col_index)

    
    

In [6]:
new_cost_matrix = [
    [9, 2, 7, 8],
    [6, 4, 3, 7],
    [5, 8, 1, 8],
    [7, 6, 9, 4]
]

start = time.time()
hungarian_method(new_cost_matrix)
end = time.time()

print(end-start)

Step 1 - Cost Matrix :
[[7 0 5 6]
 [3 1 0 4]
 [4 7 0 7]
 [3 2 5 0]]
Step 2 - Cost Matrix :
[[4 0 5 6]
 [0 1 0 4]
 [1 7 0 7]
 [0 2 5 0]]
Updated Mark Matrix:
[0, 1, 0, 0]
[0, 0, -1, 0]
[0, 0, 1, 0]
[-1, 0, 0, 1]
0.0


In [7]:
import numpy as np

def min_zero_row(zero_mat, mark_zero):
	
	'''
	The function can be splitted into two steps:
	#1 The function is used to find the row which containing the fewest 0.
	#2 Select the zero number on the row, and then marked the element corresponding row and column as False
	'''

	#Find the row
	min_row = [99999, -1]

	for row_num in range(zero_mat.shape[0]): 
		if np.sum(zero_mat[row_num] == True) > 0 and min_row[0] > np.sum(zero_mat[row_num] == True):
			min_row = [np.sum(zero_mat[row_num] == True), row_num]

	# Marked the specific row and column as False
	zero_index = np.where(zero_mat[min_row[1]] == True)[0][0]
	mark_zero.append((min_row[1], zero_index))
	zero_mat[min_row[1], :] = False
	zero_mat[:, zero_index] = False

def mark_matrix(mat):

	'''
	Finding the returning possible solutions for LAP problem.
	'''

	#Transform the matrix to boolean matrix(0 = True, others = False)
	cur_mat = mat
	zero_bool_mat = (cur_mat == 0)
	zero_bool_mat_copy = zero_bool_mat.copy()

	#Recording possible answer positions by marked_zero
	marked_zero = []
	while (True in zero_bool_mat_copy):
		min_zero_row(zero_bool_mat_copy, marked_zero)
	
	#Recording the row and column positions seperately.
	marked_zero_row = []
	marked_zero_col = []
	for i in range(len(marked_zero)):
		marked_zero_row.append(marked_zero[i][0])
		marked_zero_col.append(marked_zero[i][1])

	#Step 2-2-1
	non_marked_row = list(set(range(cur_mat.shape[0])) - set(marked_zero_row))
	
	marked_cols = []
	check_switch = True
	while check_switch:
		check_switch = False
		for i in range(len(non_marked_row)):
			row_array = zero_bool_mat[non_marked_row[i], :]
			for j in range(row_array.shape[0]):
				#Step 2-2-2
				if row_array[j] == True and j not in marked_cols:
					#Step 2-2-3
					marked_cols.append(j)
					check_switch = True

		for row_num, col_num in marked_zero:
			#Step 2-2-4
			if row_num not in non_marked_row and col_num in marked_cols:
				#Step 2-2-5
				non_marked_row.append(row_num)
				check_switch = True
	#Step 2-2-6
	marked_rows = list(set(range(mat.shape[0])) - set(non_marked_row))

	return(marked_zero, marked_rows, marked_cols)

def adjust_matrix(mat, cover_rows, cover_cols):
	cur_mat = mat
	non_zero_element = []

	#Step 4-1
	for row in range(len(cur_mat)):
		if row not in cover_rows:
			for i in range(len(cur_mat[row])):
				if i not in cover_cols:
					non_zero_element.append(cur_mat[row][i])
	min_num = min(non_zero_element)

	#Step 4-2
	for row in range(len(cur_mat)):
		if row not in cover_rows:
			for i in range(len(cur_mat[row])):
				if i not in cover_cols:
					cur_mat[row, i] = cur_mat[row, i] - min_num
	#Step 4-3
	for row in range(len(cover_rows)):  
		for col in range(len(cover_cols)):
			cur_mat[cover_rows[row], cover_cols[col]] = cur_mat[cover_rows[row], cover_cols[col]] + min_num
	return cur_mat

def hungarian_algorithm(mat): 
	dim = mat.shape[0]
	cur_mat = mat

	#Step 1 - Every column and every row subtract its internal minimum
	for row_num in range(mat.shape[0]): 
		cur_mat[row_num] = cur_mat[row_num] - np.min(cur_mat[row_num])
	
	for col_num in range(mat.shape[1]): 
		cur_mat[:,col_num] = cur_mat[:,col_num] - np.min(cur_mat[:,col_num])
	zero_count = 0
	while zero_count < dim:
		#Step 2 & 3
		ans_pos, marked_rows, marked_cols = mark_matrix(cur_mat)
		zero_count = len(marked_rows) + len(marked_cols)

		if zero_count < dim:
			cur_mat = adjust_matrix(cur_mat, marked_rows, marked_cols)

	return ans_pos

def ans_calculation(mat, pos):
	total = 0
	ans_mat = np.zeros((mat.shape[0], mat.shape[1]))
	for i in range(len(pos)):
		total += mat[pos[i][0], pos[i][1]]
		ans_mat[pos[i][0], pos[i][1]] = mat[pos[i][0], pos[i][1]]
	return total, ans_mat

def main():

	'''Hungarian Algorithm: 
	Finding the minimum value in linear assignment problem.
	Therefore, we can find the minimum value set in net matrix 
	by using Hungarian Algorithm. In other words, the maximum value
	and elements set in cost matrix are available.'''

	#The matrix who you want to find the minimum sum
	cost_matrix = np.array([
    [9, 2, 7, 8],
    [6, 4, 3, 7],
    [5, 8, 1, 8],
    [7, 6, 9, 4]
])
	
	ans_pos = hungarian_algorithm(cost_matrix.copy())#Get the element position.
	ans, ans_mat = ans_calculation(cost_matrix, ans_pos) #Get the minimum or maximum value and corresponding matrix.

	#Show the result
	print(f"Linear Assignment problem result: {ans:.0f}\n{ans_mat}")

if __name__ == '__main__':
	main()

Linear Assignment problem result: 13
[[0. 2. 0. 0.]
 [6. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 4.]]
