## Dynamic Programming

https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/

ปัญหาคือ Knapsack problem กับ Dynamic programming มันจะเอาค่าที่สูงสุดที่ขวาล่างตาราง แล้วเราจะรู้ได้ไงว่า Minimum cost อยู่ตรงไหน??

อาจจะลองเอานี้ไปคิดต่อ หรือ ลองหาอันอื่นดูนะ

<img src="problem.PNG" width="600px">

Final

In [36]:
import numpy as np

def knapsack(cities, days, costs, max_days):
    n = len(cities)
    worthiness = [cost / day for cost, day in zip(costs, days)]  # หาสัดส่วนความคุ้มค่า
    dp = [[0] * (max_days + 1) for _ in range(n + 1)]

    for i in range(1, n + 1):
        for j in range(1, max_days + 1):
            if days[i - 1] <= j:
                dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - days[i - 1]] + worthiness[i - 1])  # ใช้ worthiness ในการพิจารณา
            else:
                dp[i][j] = dp[i - 1][j]

    selected_cities = []
    i, j = n, max_days
    while i > 0 and j > 0:
        if dp[i][j] != dp[i - 1][j]:
            selected_cities.append(cities[i - 1])
            j -= days[i - 1]
        i -= 1

    # Calculate total cost of selected cities
    total_cost = sum(costs[cities.index(city)] for city in selected_cities)

    print(np.array(dp))

    return total_cost, selected_cities

cities = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
costs = [80, 85, 100, 45, 75, 25, 148, 205, 24, 200]
max_days = 14

min_cost, selected_cities = knapsack(cities, days, costs, max_days)
print("Minimum cost:", min_cost)
print("Selected cities:", selected_cities)

[[  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.          26.66666667  26.66666667
   26.66666667  26.66666667  26.66666667  26.66666667  26.66666667
   26.66666667  26.66666667  26.66666667  26.66666667  26.66666667]
 [  0.           0.           0.          26.66666667  26.66666667
   26.66666667  26.66666667  47.91666667  47.91666667  47.91666667
   47.91666667  47.91666667  47.91666667  47.91666667  47.91666667]
 [  0.           0.           0.          26.66666667  26.66666667
   26.66666667  26.66666667  47.91666667  47.91666667  47.91666667
   47.91666667  47.91666667  67.91666667  67.91666667  67.91666667]
 [  0.           0.          22.5         26.66666667  26.66666667
   49.16666667  49.16666667  49.16666667  49.16666667  70.41666667
   70.41666667  70.41666667  70.41666667  70.41666667  90.41666667]
 [  0.

In [12]:
import numpy as np

def knapSack(W, wt, val, n):
    K = [[0 for x in range(W + 1)] for x in range(n + 1)]

    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                K[i][w] = 0
            elif wt[i-1] <= w:
                K[i][w] = max(val[i-1]
                              + K[i-1][w-wt[i-1]],
                              K[i-1][w])
            else:
                K[i][w] = K[i-1][w]

    # Data Visualization
    print(np.array(K))

    return K[n][W]

In [13]:
cost = [80,85,100,45,75,25,148,205,24,200]
weight = [3,4,5,2,3,1,6,8,1,7]
# Data normalization
W = 14  # Maximum days limit
n = len(cost)
print(knapSack(W, weight, cost, n))

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  80  80  80  80  80  80  80  80  80  80  80  80]
 [  0   0   0  80  85  85  85 165 165 165 165 165 165 165 165]
 [  0   0   0  80  85 100 100 165 180 185 185 185 265 265 265]
 [  0   0  45  80  85 125 130 165 180 210 225 230 265 265 310]
 [  0   0  45  80  85 125 155 165 200 210 240 255 285 300 310]
 [  0  25  45  80 105 125 155 180 200 225 240 265 285 310 325]
 [  0  25  45  80 105 125 155 180 200 228 253 273 303 328 348]
 [  0  25  45  80 105 125 155 180 205 230 253 285 310 330 360]
 [  0  25  49  80 105 129 155 180 205 230 254 285 310 334 360]
 [  0  25  49  80 105 129 155 200 225 249 280 305 329 355 380]]
380


In [11]:
def knapSack(W, wt, val, n):
    K = [[0 for x in range(W + 1)] for x in range(n + 1)]

    # Build table K[][] in bottom up manner
    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                K[i][w] = 0
            elif wt[i-1] <= w:
                K[i][w] = max(val[i-1] + K[i-1][w-wt[i-1]], K[i-1][w]) # Change min to max
            else:
                K[i][w] = K[i-1][w]

    return K

# Test data
cities = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cost = [80, 85, 100, 45, 75, 25, 50, 205, 24, 200]
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
day_limit = 14

# Generate the matrix for number of cities visited
num_cities_matrix = knapSack(day_limit, days, [1] * len(cities), len(cities))

# Print the matrix
for i in range(len(num_cities_matrix)):
    print(num_cities_matrix[i])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]
[0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3]
[0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4]
[0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4]
[0, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5]
[0, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5]
[0, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5]
[0, 1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6]
[0, 1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6]


In [20]:
import numpy as np

def knapSack(W, wt, val, n):
    score_matrix = [[0 for x in range(W + 1)] for x in range(n + 1)]

    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                score_matrix[i][w] = 0
            elif wt[i-1] <= w:
                include_score = (1 / val[i-1]) * ((score_matrix[i-1][w-wt[i-1]] + 1) / n)
                exclude_score = score_matrix[i-1][w]
                score_matrix[i][w] = max(include_score, exclude_score)
            else:
                score_matrix[i][w] = score_matrix[i-1][w]

    return score_matrix

# Test data
cities = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cost = [80, 85, 100, 45, 75, 25, 50, 205, 24, 200]
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
day_limit = 14

# Generate the score matrix
score_matrix = knapSack(day_limit, days, cost, len(cities))

# Print the score matrix
print("Score Matrix:")
print(np.array(score_matrix))

Score Matrix:
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.00125    0.00125    0.00125
  0.00125    0.00125    0.00125    0.00125    0.00125    0.00125
  0.00125    0.00125    0.00125   ]
 [0.         0.         0.         0.00125    0.00125    0.00125
  0.00125    0.00125    0.00125    0.00125    0.00125    0.00125
  0.00125    0.00125    0.00125   ]
 [0.         0.         0.         0.00125    0.00125    0.00125
  0.00125    0.00125    0.00125    0.00125    0.00125    0.00125
  0.00125    0.00125    0.00125   ]
 [0.         0.         0.00222222 0.00222222 0.00222222 0.002225
  0.002225   0.002225   0.002225   0.002225   0.002225   0.002225
  0.002225   0.002225   0.002225  ]
 [0.         0.         0.00222222 0.00222222 0.00222222 0.002225
  0.002225   0.002225   0.002225   0.002225   0.002225   0.002225
  0.002225   0.002225   0.002225

In [23]:
import numpy as np

def knapSack(W, wt, val, n):
    score_matrix = [[0 for x in range(W + 1)] for x in range(n + 1)]

    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                score_matrix[i][w] = 0
            elif wt[i-1] <= w:
                include_score = (1 / val[i-1]) * (np.exp(score_matrix[i-1][w-wt[i-1]] + 1) / n)
                exclude_score = score_matrix[i-1][w]
                score_matrix[i][w] = max(include_score, exclude_score)
            else:
                score_matrix[i][w] = score_matrix[i-1][w]

    return score_matrix

# Test data
cities = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cost = [80, 85, 100, 45, 75, 25, 50, 205, 24, 200]
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
day_limit = 14

# Generate the score matrix
score_matrix = knapSack(day_limit, days, cost, len(cities))

# Print the score matrix
print("Score Matrix:")
print(np.array(score_matrix))

Score Matrix:
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.00339785 0.00339785 0.00339785
  0.00339785 0.00339785 0.00339785 0.00339785 0.00339785 0.00339785
  0.00339785 0.00339785 0.00339785]
 [0.         0.         0.         0.00339785 0.00339785 0.00339785
  0.00339785 0.00339785 0.00339785 0.00339785 0.00339785 0.00339785
  0.00339785 0.00339785 0.00339785]
 [0.         0.         0.         0.00339785 0.00339785 0.00339785
  0.00339785 0.00339785 0.00339785 0.00339785 0.00339785 0.00339785
  0.00339785 0.00339785 0.00339785]
 [0.         0.         0.00604063 0.00604063 0.00604063 0.00606119
  0.00606119 0.00606119 0.00606119 0.00606119 0.00606119 0.00606119
  0.00606119 0.00606119 0.00606119]
 [0.         0.         0.00604063 0.00604063 0.00604063 0.00606119
  0.00606119 0.00606119 0.00606119 0.00606119 0.00606119 0.00606119
  0.00

In [25]:
import numpy as np

def knapSack(W, wt, val, n):
    score_matrix = [[0 for x in range(W + 1)] for x in range(n + 1)]

    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                score_matrix[i][w] = 0
            elif wt[i-1] <= w:
                include_score = ((1 / val[i-1]) * (np.exp(score_matrix[i-1][w-wt[i-1]] + 1) / n)) * (1 / (w + 1)) * (1 / (np.sqrt(np.sum(wt[:i])) + 1))
                exclude_score = score_matrix[i-1][w]
                score_matrix[i][w] = max(include_score, exclude_score)
            else:
                score_matrix[i][w] = score_matrix[i-1][w]

    return score_matrix

# Test data
cities = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cost = [80, 85, 100, 45, 75, 25, 50, 205, 24, 200]
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
day_limit = 14

# Generate the score matrix
score_matrix = knapSack(day_limit, days, cost, len(cities))

# Print the score matrix
print("Score Matrix:")
print(np.array(score_matrix))

Score Matrix:
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.10925064e-04
  2.48740051e-04 2.07283376e-04 1.77671465e-04 1.55462532e-04
  1.38188917e-04 1.24370025e-04 1.13063660e-04 1.03641688e-04
  9.56692504e-05 8.88357325e-05 8.29133503e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.10925064e-04
  2.48740051e-04 2.07283376e-04 1.77671465e-04 1.55462532e-04
  1.38188917e-04 1.24370025e-04 1.13063660e-04 1.03641688e-04
  9.56692504e-05 8.88357325e-05 8.29133503e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.10925064e-04
  2.48740051e-04 2.07283376e-04 1.77671465e-04 1.55462532e-04
  1.38188917e-04 1.24370025e-04 1.13063660e-04 1.03641688e-04
  9.56692504e-05 8.88357325e-05 8.29133503e-05]
 [0.00000000e+00 0.00000000e+00 4.24649428e-04 3.1

In [26]:
import numpy as np

def knapSack(W, wt, val, n):
    score_matrix = [[[0, []] for x in range(W + 1)] for x in range(n + 1)]

    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                score_matrix[i][w] = [0, []]
            elif wt[i-1] <= w:
                include_score = ((1 / val[i-1]) * (np.exp(score_matrix[i-1][w-wt[i-1]][0] + 1) / n)) * (1 / (w + 1)) * (1 / (np.sqrt(np.sum(wt[:i])) + 1))
                exclude_score = score_matrix[i-1][w][0]
                if include_score > exclude_score:
                    included_cities = score_matrix[i-1][w-wt[i-1]][1] + [i-1]
                    score_matrix[i][w] = [include_score, included_cities]
                else:
                    score_matrix[i][w] = [exclude_score, score_matrix[i-1][w][1]]
            else:
                score_matrix[i][w] = score_matrix[i-1][w]

    return score_matrix

# Test data
cities = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cost = [80, 85, 100, 45, 75, 25, 50, 205, 24, 200]
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
day_limit = 14

# Generate the score matrix
score_matrix = knapSack(day_limit, days, cost, len(cities))

# Find the cell with the highest score
max_score_cell = max((score_matrix[i][w], i, w) for i in range(len(score_matrix)) for w in range(len(score_matrix[i])))

# Extract selected cities and total cost corresponding to the cell with the highest score
selected_cities_indices = max_score_cell[0][1]
selected_cities = [cities[i] for i in selected_cities_indices]
total_cost = sum(cost[i] for i in selected_cities_indices)
total_days = sum(days[i] for i in selected_cities_indices)

# Print the selected cities and total cost
print("Selected Cities:", selected_cities)
print("Total Cost:", total_cost)
print("Total Days:", total_days)

Selected Cities: ['F']
Total Cost: 25
Total Days: 1


In [2]:
import numpy as np

def knapSack(W, wt, val, n):
    score_matrix = [[[0, []] for _ in range(W + 1)] for _ in range(n + 1)]

    for i in range(1, n + 1):
        for w in range(1, W + 1):
            if wt[i-1] <= w:
                include_score = 1 / (1 + days_diff) * 1 / total_cost * len(visited_cities)
                exclude_score = score_matrix[i-1][w][0]

                if include_score > exclude_score:
                    included_cities = score_matrix[i-1][w-wt[i-1]][1] + [i-1]
                    score_matrix[i][w] = [include_score, included_cities]
                else:
                    score_matrix[i][w] = [exclude_score, score_matrix[i-1][w][1]]
            else:
                score_matrix[i][w] = score_matrix[i-1][w]

    return score_matrix

# Test data
cities = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cost = [80, 85, 100, 45, 75, 25, 50, 205, 24, 200]
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
day_limit = 14

# Generate the score matrix
score_matrix = knapSack(day_limit, days, cost, len(cities))

# Find the cell with the highest score
max_score_cell = max((score_matrix[i][w], i, w) for i in range(len(score_matrix)) for w in range(len(score_matrix[i])))

# Extract selected cities and total cost corresponding to the cell with the highest score
selected_cities_indices = max_score_cell[0][1]
selected_cities = [cities[i] for i in selected_cities_indices]
total_cost = sum(cost[i] for i in selected_cities_indices)
total_days = sum(days[i] for i in selected_cities_indices)

# Calculate the score based on the differences between total days and maximum allowed days, and number of cities visited and desired maximum cities
score = max_score_cell[0][0]
days_difference = abs(14 - total_days)
cities_difference = abs(10 - len(selected_cities))
score += 1 / (days_difference + 1)
score += 1 / (cities_difference + 1)

# Print the selected cities, total cost, and score
print("Selected Cities:", selected_cities)
print("Total Cost:", total_cost)
print("Total Days:", total_days)
print("Score:", score)

NameError: name 'days_diff' is not defined

In [7]:
import numpy as np

def knapSack(W, wt, val, n):
    score_matrix = [[[0, []] for _ in range(W + 1)] for _ in range(n + 1)]

    for i in range(1, n + 1):
        for w in range(1, W + 1):
            if wt[i-1] <= w:
                days_diff = abs(W - w)  # Difference between maximum allowed days (W) and current weight (w)
                total_cost = sum(val[:i])  # Total cost considering the current selection
                visited_cities = set(range(i))  # Unique cities visited considering the current selection

                # Calculate include_score
                include_score = 1 / (1 + days_diff) * 1 / total_cost * len(visited_cities)
                
                exclude_score = score_matrix[i-1][w][0]

                if include_score > exclude_score:
                    included_cities = score_matrix[i-1][w-wt[i-1]][1] + [i-1]
                    score_matrix[i][w] = [include_score, included_cities]
                else:
                    score_matrix[i][w] = [exclude_score, score_matrix[i-1][w][1]]
            else:
                score_matrix[i][w] = score_matrix[i-1][w]

    return score_matrix

# Test data
cities = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cost = [80, 85, 100, 45, 75, 25, 148, 205, 24, 200]
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
day_limit = 14

# Generate the score matrix
score_matrix = knapSack(day_limit, days, cost, len(cities))

# Find the cell with the highest score
max_score_cell = max((score_matrix[i][w], i, w) for i in range(len(score_matrix)) for w in range(len(score_matrix[i])))

# Extract selected cities and total cost corresponding to the cell with the highest score
selected_cities_indices = max_score_cell[0][1]
selected_cities = [cities[i] for i in selected_cities_indices]
total_cost = sum(cost[i] for i in selected_cities_indices)
total_days = sum(days[i] for i in selected_cities_indices)

# Calculate the score based on the differences between total days and maximum allowed days, and number of cities visited and desired maximum cities
score = max_score_cell[0][0]
days_difference = abs(day_limit - total_days)
cities_difference = abs(len(cities) - len(selected_cities))
score += 1 / (days_difference + 1)
score += 1 / (cities_difference + 1)

# Print the selected cities, total cost, and score
print("Selected Cities:", selected_cities)
print("Total Cost:", total_cost)
print("Total Days:", total_days)
print("Score:", score)

Selected Cities: ['A', 'D', 'E', 'F']
Total Cost: 225
Total Days: 9
Score: 0.3241579558652729


In [9]:
import numpy as np

def knapSack(W, wt, val, n):
    score_matrix = [[[0, []] for _ in range(W + 1)] for _ in range(n + 1)]

    for i in range(1, n + 1):
        for w in range(1, W + 1):
            if wt[i-1] <= w:
                # Difference between maximum allowed days (W) and current weight (w)
                days_diff = abs(W - w)
                # Total cost considering the current selection
                total_cost = sum(val[:i])
                # Unique cities visited considering the current selection
                visited_cities = set(range(i))

                # Calculate include_score
                # Adjusted formula to prioritize higher number of cities visited
                include_score = (len(visited_cities) + 1) / (1 + days_diff) * 1 / total_cost
                
                exclude_score = score_matrix[i-1][w][0]

                if include_score > exclude_score:
                    included_cities = score_matrix[i-1][w-wt[i-1]][1] + [i-1]
                    score_matrix[i][w] = [include_score, included_cities]
                else:
                    score_matrix[i][w] = [exclude_score, score_matrix[i-1][w][1]]
            else:
                score_matrix[i][w] = score_matrix[i-1][w]

    return score_matrix

# Test data
cities = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cost = [80, 85, 100, 45, 75, 25, 148, 205, 24, 200]
days = [3, 4, 5, 2, 3, 1, 6, 8, 1, 7]
day_limit = 14

# Generate the score matrix
score_matrix = knapSack(day_limit, days, cost, len(cities))

# Find the cell with the highest score
max_score_cell = max((score_matrix[i][w], i, w) for i in range(len(score_matrix)) for w in range(len(score_matrix[i])))

# Extract selected cities and total cost corresponding to the cell with the highest score
selected_cities_indices = max_score_cell[0][1]
selected_cities = [cities[i] for i in selected_cities_indices]
total_cost = sum(cost[i] for i in selected_cities_indices)
total_days = sum(days[i] for i in selected_cities_indices)

# Calculate the score based on the differences between total days and maximum allowed days, and number of cities visited and desired maximum cities
score = max_score_cell[0][0]
days_difference = abs(day_limit - total_days)
cities_difference = abs(len(cities) - len(selected_cities))
score += 1 / (days_difference + 1)
score += 1 / (cities_difference + 1)

# Print the selected cities, total cost, and score
print("Selected Cities:", selected_cities)
print("Total Cost:", total_cost)
print("Total Days:", total_days)
print("Score:", score)

Selected Cities: ['A']
Total Cost: 80
Total Days: 3
Score: 0.20833333333333334
