# Week 5 - Transform and Conquer 
(สรุปสิ่งที่ได้เรียนรู้ในสัปดาห์นี้)

* Transform and Conquer คือ อัลกอริทึมที่มีการเปลี่ยนแปลงรูปแบบของปัญหาหรือสิ่งต่างๆ ก่อนที่จะทำการแก้ปัญหา เนื่องจากปัญหาเดิมสามารถแก้ได้ยาก ทำให้เราต้องปรับเปลี่ยนรูปแบบก่อนที่จะแก้
- Transformation stage (ขั้นตอนในการเปลี่ยนแปลงรูปแบบปัญหา) มีทั้งหมด 3 รูปแบบ ได้แก่
  1. Instance simplification - Simplify หรือเปลี่ยนแปลง Problem Instance ให้ง่ายขึ้น
  2. Representation change - เปลี่ยนรูปแบบ Data Structures หรือ Database ที่เก็บ
  3. Problem reduction - เปลี่ยนเป็นปัญหาอื่นที่รู้วิธีแก้ไขแล้วค่อยย้อนกลับมาแก้ปัญหาต้นฉบับ

- Solution stage ขั้นตอนในการแก้ปัญหาเสร็จแล้ว

* Instance Simplification ได้แก่
  - Presorting คือ การเรียงลำดับก่อนที่จะแก้ไขปัญหา
  - Gaussian Elimination คือ การแก้ไขปัญหาสมการเชิงเส้น (Linear Equation) ด้วยการมองเป็นเมทริกซ์ Ax = B <br> โดยประกอบด้วย Forward Elimination, Better Forward Elimination และ LU Decomposition
  - Forward Elimination คือการทำเมทริกซ์แต่งเติมให้กลายเป็น Upper-triangle matrix
  - Better Forward Elimination เกิดขึ้นเนื่องจากปัญหา การหารด้วย 0 และ Round-off error (ค่าสูงมากๆ) <br> โดยที่ Better Forward Elimination ใช้หลักการ Partial Pivoting เพื่อหาใน row ว่าตัว A[i,i] จะสูง
  - LU Decomposition คือเทคนิคที่ทำให้กระบวนการ Gaussian Elimination ง่ายขึ้น โดยการแปลงเป็น Upper-triangle <br> กับ Lower-triangle Matrix เพื่อให้ง่ายขึ้นต่อการคำนวณ
  - AVL trees, Red-black trees, splay trees

* Representation Change (การเปลี่ยนหน้าตา Database) ได้แก่
  - 2-3 trees, 2-3-4 trees <br>
  เนื่องจากการทำ BST (Balanced Search Tree) ทำให้มันแตกกิ่งซ้ายขวาให้เท่ากัน เพื่อที่จะหาข้อมูลได้ไวขึ้น เป็น O(logn) <br>
  แต่ว่าปัญหา BST ที่มันไม่ Balanced ก็จะแตกกิ่งเรื่อยๆ BST ไม่ช่วยอะไร O(n) เหมือนเดิม <br>
  โดยหลักการของ 2-3 trees คือการที่ โหนดจะมีลูกทางด้านซ้าย คือค่าน้อยกว่า ค่าน้อยที่สุดในโหนดแม่ โหนดลูกทางขวา <br> มีค่ามากกว่า ค่ามากที่สุดในโหนดแม่ ส่วนโหนดลูกตรงกลางคือค่าที่อยู่ระหว่างค่าสองค่าจากโหนดแม่
  - Algorithms ของการทำ 2-3 Trees คือ เพิ่ม Element ไปที่ Leaf Node จากนั้นจัดตามเงื่อนไขด้านบนเพื่อให้ได้ 2-3 trees
  - B-trees


* Problem Reduction (เปลี่ยนรูปแบบไปปัญหาอื่นๆ ที่รู้คำตอบอยู่แล้ว แล้วค่อยแปลงกลับมา)
  - LCM (Least common multiple) - การหาครน. โดยเราสามารถไปหา หรม. (gcd) ซึ่งเราเขียนอัลกอริทึมไว้อยู่แล้ว จากนั้นเข้าสมการดังนี้


<div style="text-align : center;">
<img src="https://lh3.googleusercontent.com/Xb8a1tjxAi8cGidjwKLRJ5Ehar0YZ1fzYmpyeU23d3-tHCXr-qjSDN0t1FBvNuNf_JgTF17PPtRq5S6126FOFurzz0NEkYNrViPwwZ7Ad3ettDdPOsfr--V9duT_uSbGHvi1N61M">
</div>

   - Counting a Path in a Graph (การหาเส้นทางที่ผ่านจากจุด เช่นผ่าน Vertrices ทั้งหมดกี่ครั้ง)
เราสามารถเปลี่ยนแปลงให้อยู่ในรูปของปัญหา Matrix ได้แทนโดยการทำ Adjacency Matrix และทำการยกกำลัง Matrix ด้วยค่าที่ต้องการจะรู้ว่าใช้กี่ Vertrices (Paths of lengths)
- การทำ Optimization Problems ยกตัวอย่างเช่น การแก้ปัญหา Maximization ด้วยการหา Minimization หรือในทางกลับกันก็สามารถทำได้

---

### Instance Simplification

การทำให้ Instance ของปัญหาง่ายลงในการแก้ไข

### Unique Element

In [1]:
def UniqueElement(my_list):
    n = len(my_list)
    for i in range(n):
        for j in range(i+1, n):
            if my_list[i] == my_list[j]:
                return False
    return True

In [2]:
# Test case 1 : Unique Element All element are not distinct

my_list = [12, 38, 42, 64, 53, 43, 55, 34, 45, 64, 90, 82]
check = UniqueElement(my_list)
print('All elements are distinct :',check)

All elements are distinct : False


In [3]:
# Test case 2 : Unique Element All element are distinct

my_list = [5, 12, 38, 40, 64, 55, 43, 56, 34, 45, 91, 54]
check = UniqueElement(my_list)
print('All elements are distinct :',check)

All elements are distinct : True


---

### Presorting Unique Element

In [4]:
def BubbleSort(my_list):
    n = len(my_list)
    for i in range(n-1):
        for j in range(0, n-i-1):
            if my_list[j] > my_list[j+1]:
                my_list[j], my_list[j+1] = my_list[j+1], my_list[j]
                

def PresortUniqueElements(my_list):
    BubbleSort(my_list)
    print("My_list after sorted :",my_list)
    n = len(my_list)
    for i in range(n-1):
        if my_list[i] == my_list[i+1]:
            return False
    return True

In [5]:
# Test case 1 : all element are not distinct

my_list = [12, 38, 42, 64, 53, 43, 55, 34, 45, 64, 90, 82]
check = PresortUniqueElements(my_list)
print('All elements are distinct :',check)

My_list after sorted : [12, 34, 38, 42, 43, 45, 53, 55, 64, 64, 82, 90]
All elements are distinct : False


In [6]:
# Test case 2 : all element are distinct

my_list = [5, 12, 38, 40, 64, 55, 43, 56, 34, 45, 91, 54]
check = PresortUniqueElements(my_list)
print('All elements are distinct :',check)

My_list after sorted : [5, 12, 34, 38, 40, 43, 45, 54, 55, 56, 64, 91]
All elements are distinct : True


---

### Brute Force Mode

In [26]:
def BruteForceMode(my_list):
    freq = {}
    for number in my_list:
        if number not in freq:
            freq[number] = 1
        else:
            freq[number] += 1

    # กรณีมี Mode หลายค่า
    mode_key = []
    mode = max(freq.values())

    # ถ้าหากค่าน้อยกว่า 1 แสดงว่าตามทฤษฏีมันไม่มีค่า Mode
    if mode <= 1:
        return None

    for key, value in freq.items():
        if value == mode:
            mode_key.append(key)

    return mode_key

In [30]:
# Test Case 1 - Brute Force Mode

my_list = [1, 1, 1, 1, 1, 2, 2, 3, 4, 5, 6, 7, 1]
all_keys = BruteForceMode(my_list)
print('Mode :',all_keys)

Mode : [1]


In [27]:
# Test Case 2 - Brute Force Mode

my_list = [1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
all_keys = BruteForceMode(my_list)
print("Mode is :", all_keys)

Mode is : [1, 3]


In [28]:
# Test Case 3 - Brute Force Mode

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
all_keys = BruteForceMode(my_list)
print("Mode is :", all_keys)

Mode is : None


---

### Presorting Mode

In [31]:
def BubbleSort(my_list):
    n = len(my_list)
    for i in range(n-1):
        for j in range(0, n-i-1):
            if my_list[j] > my_list[j+1]:
                my_list[j], my_list[j+1] = my_list[j+1], my_list[j]

def PresortMode(my_list):
    BubbleSort(my_list)
    n = len(my_list)
    i = 0 # current run begins at position i
    mode_freq = 0 # highest frequency seen so far
    while i <= n-1:

        run_len = 1
        run_value = my_list[i]

        while i+run_len <= n-1 and my_list[i+run_len] == run_value:
            run_len += 1
            
        if run_len > mode_freq:
            mode_freq = run_len
            mode_value = run_value
        i += run_len
    return mode_value , mode_freq

In [32]:
# Test case 1 : Presorting Mode

my_list = [6,3,2,9,1,3,6,6,2,3,1,3,2,6,9,3,2,1,3]
result = PresortMode(my_list)
value , freq = result[0] , result[1]
print("The array's mode is" , value)
print("With frequency" , freq)

The array's mode is 3
With frequency 6


In [35]:
# Test Case 2 : Presorting Mode

my_list = [1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 1]
result = PresortMode(my_list)
value , freq = result[0] , result[1]
print("The array's mode is" , value)
print("With frequency" , freq)

The array's mode is 1
With frequency 8


---

### Gaussian Elimination

In [17]:
def ForwardElimination(A,B):

    # A - Matrix[1..n , 1..n]
    # B - column vector b[1..n]

    # Increase the column in every row เพื่อที่จะใส่เมทริกซ์ B แปะเข้าไปด้วย
    A = A.copy()
    for row in A:
        row.append(0)
         
    n = len(A)

    for i in range(n):
        A[i][n] = B[i]

    for i in range(n-1):
        for j in range(i+1 ,n):
            for k in range(i,n+1):
                    A[j][k] = int( A[j][k] - A[i][k] * (A[j][i] / A[i][i]) )

    return A

In [19]:
# Test Case 1 - Forward Elimination

import numpy as np # for data visualization
A = [[2, 1, -1], [-3, -1, 2], [-2, 1, 2]]
B = [8, -11, -3]
M = ForwardElimination(A,B)
M = np.array(M)

print("Augmented Matrix after Forward Elimination :")
print(M)

print("\n Matrix A : ")
print(M[:,:3]) # เอาทุกแถว แต่เอาแค่ หลักจนถึง 3

print("\n Matrix B : ")
print(M[:,3]) # เอาทุกแถว แต่เอาแค่ หลักที่ 4

# เมทริกซ์ 3 คอลัมน์แรก คือ เมทริกซ์ A แต่คอลัมน์ที่ 4 คือ B ที่มาติดด้วยเวลาทำ Row Operation

Augmented Matrix after Forward Elimination :
[[  2   1  -1   8]
 [  0  -1   2 -11]
 [  0   0   2  -3]]

 Matrix A : 
[[ 2  1 -1]
 [ 0 -1  2]
 [ 0  0  2]]

 Matrix B : 
[  8 -11  -3]


In [20]:
# Test Case 2 - Forward Elimination

A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [10, 11, 12]
M = ForwardElimination(A,B)
M = np.array(M)

print("Augmented Matrix after Forward Elimination :")
print(M)

print("\n Matrix A : ")
print(M[:,:3])

print("\n Matrix B : ")
print(M[:,3])

Augmented Matrix after Forward Elimination :
[[ 1  2  3 10]
 [ 0  5  6 11]
 [ 0  0  9 12]]

 Matrix A : 
[[1 2 3]
 [0 5 6]
 [0 0 9]]

 Matrix B : 
[10 11 12]


---

### Better Forward Elimination

In [29]:
def BetterForwardElimination(A,B):

    # แปะเมทริกซ์ B ในแต่ละแถว เพิ่มเป็น 0
    A = A.copy()
    for row in A:
        row.append(0)
        
    n = len(A)

    for i in range(n):
        A[i][n] = B[i]

    for i in range(n-1):

        pivotrow = i
        for j in range(i+1, n):
            if abs(A[j][i]) > abs(A[pivotrow][i]):
                pivotrow = j
        for k in range(i, n+1):
            A[i][k], A[pivotrow][k] = A[pivotrow][k], A[i][k]

        for j in range(i+1, n):
            
            temp = A[j][i] / A[i][i]
            for k in range(i,n+1):
                A[j][k] = int( A[j][k] - (temp * A[i][k]) )
                
    return A

In [30]:
# Test case 1 - Better Forward Elimination
import numpy as np # for data visualization

A = [[2, 1, -1], [-3, -1, 2], [-2, 1, 2]]
B = [8, -11, -3]
M = BetterForwardElimination(A,B)
M = np.array(M)

print("Augmented Matrix after Better Forward Elimination :" + "\n", M)

print("\n Matrix A : ")
print(M[:,:3])

print("\n Matrix B : ")
print(M[:,3])

Augmented Matrix after Better Forward Elimination :
 [[ -3  -1   2 -11]
 [  0   1   0   4]
 [  0   0   0   0]]

 Matrix A : 
[[-3 -1  2]
 [ 0  1  0]
 [ 0  0  0]]

 Matrix B : 
[-11   4   0]


In [34]:
# Test case 2 - Better Forward Elimination

A = [[4, 2, 3], [1, 5, 6], [7, 8, 9]]
B = [10, 11, 12]

M = BetterForwardElimination(A,B)
M = np.array(M)

print("Augmented Matrix after Better Forward Elimination :" + "\n", M)

print("\n Matrix A : ")
print(M[:,:3])

print("\n Matrix B : ")
print(M[:,3])


Augmented Matrix after Better Forward Elimination :
 [[ 7  8  9 12]
 [ 0  3  4  9]
 [ 0  0  0  9]]

 Matrix A : 
[[7 8 9]
 [0 3 4]
 [0 0 0]]

 Matrix B : 
[12  9  9]


---

### Assignment 2 - LU Decomposition เพื่อหา Matrix Inversion

# Problem Reduction

### Least Common Mutliple (LCM) Time Experimental

In [1]:
# Normal Least common multiple

def prime_factorization(number):
    factors = []
    for i in range(2, number):
        while number % i == 0:
            factors.append(i)
            number = number / i
    return factors

def lcm(a, b):
    
    a_list = prime_factorization(a)
    b_list = prime_factorization(b)
    
    common = []
    for value in a_list:
        if value in b_list:
            common.append(value)
            b_list.remove(value)
        else:
            common.append(value)
            
    common.extend(b_list)
    
    print(common)
    
    total = 1
    for value in common:
        total *= value
        
    return total

In [2]:
# Test Case 1 - Normal LCM

print(lcm(20, 40)) # 5

[2, 2, 5, 2]
40


In [3]:
# Test Case 2 - Normal LCM

print(lcm(3750, 15000)) # 60

[2, 3, 5, 5, 5, 5, 2, 2]
15000


In [41]:
# Least Common Multiple using problem reduction by GCD
def gcd(m, n):
    
    while m % n != 0:
        old_m = m
        old_n = n
        
        m = old_n
        n = old_m % old_n
    return n

def lcm(a,b):
    return a * b // gcd(a,b)

In [42]:
# Test Case 1 - LCM using GCD

print(lcm(20, 40)) # 40

40


In [43]:
# Test Case 2 - LCM using GCD

print(lcm(3570, 15000)) # 60

1785000
