# Instance Simplication

In [114]:
def UniqueElement(my_list):
    n = len(my_list)
    for i in range(n):
        for j in range(i+1, n):
            if my_list[i] == my_list[j]:
                return False
    return True

In [115]:
# Test case : All element are not distinct
my_list = [12, 38, 42, 64, 53, 43, 55, 34, 45, 64, 90, 82]
check = UniqueElement(my_list)
print('All elements are distinct :',check)

All elements are distinct : False


In [116]:
# Test case : All element are distinct
my_list = [5, 12, 38, 40, 64, 55, 43, 56, 34, 45, 91, 54]
check = UniqueElement(my_list)
print('All elements are distinct :',check)

All elements are distinct : True


# Presorting

In [117]:
def BubbleSort(my_list):
    n = len(my_list)
    for i in range(n-1):
        for j in range(0, n-i-1):
            if my_list[j] > my_list[j+1]:
                my_list[j], my_list[j+1] = my_list[j+1], my_list[j]

def PresortUniqueElements(my_list):
    BubbleSort(my_list)
    print("My_list after sorted :",my_list)
    n = len(my_list)
    for i in range(n-1):
        if my_list[i] == my_list[i+1]:
            return False
    return True

In [118]:
# Test case : all element are not distinct
my_list = [12, 38, 42, 64, 53, 43, 55, 34, 45, 64, 90, 82]
check = PresortUniqueElements(my_list)
print('All elements are distinct :',check)

My_list after sorted : [12, 34, 38, 42, 43, 45, 53, 55, 64, 64, 82, 90]
All elements are distinct : False


In [119]:
# Test case : all element are distinct
my_list = [5, 12, 38, 40, 64, 55, 43, 56, 34, 45, 91, 54]
check = PresortUniqueElements(my_list)
print('All elements are distinct :',check)

My_list after sorted : [5, 12, 34, 38, 40, 43, 45, 54, 55, 56, 64, 91]
All elements are distinct : True


# Presorting Mode

In [36]:
def PresortMode(my_list):
    BubbleSort(my_list)
    n = len(my_list)
    i = 0
    mode_freq = 0
    while i <= n-1:
        run_len = 1
        run_value = my_list[i]
        while i+run_len <= n-1 and my_list[i+run_len] == run_value:
            run_len += 1
        if run_len > mode_freq:
            mode_freq = run_len
            mode_value = run_value
        i += run_len
    return mode_value

In [38]:
# Test case
my_list = [6,3,2,9,1,3,6,6,2,3,1,3,2,6,9,3,2,1,3]
check = PresortMode(my_list)
print("The array's mode is", check)

The array's mode is 3


# Gaussian Elimination

#### Forward Elimination

In [100]:
def ForwardElimination(A,B):
    n = len(A)
    for i in range(n):
        A[i,-1] = B[i]
    for i in range(n-1):
        for j in range(i+1 ,n):
            for k in range(n+1):
                if k < A.shape[1]: 
                    A[j,k] = A[j,k] - (A[j,i] / A[i,i]) * A[i,k]

In [101]:
# Test case
import numpy as np
A = np.array([[3,  1, 1],
              [-1, 2, 0],
              [4, 5, -2]], dtype=int)

B = np.array([4, 5, -10], dtype=int)

ForwardElimination(A, B)
print("Matrix 'A' after Forward Elimination:" + "\n", A)

Matrix 'A' after Forward Elimination:
 [[  3   1   4]
 [  0   2   5]
 [  0   0 -10]]


#### Better Forward Elimination

In [112]:
def BetterForwardElimination(A,B):
    n = len(A)
    for i in range(n):
        A[i,-1] = B[i]
    for i in range(n-1):
        pivotrow = i
        for j in range(i+1, n):
            if abs(A[j,i]) > abs(A[pivotrow,i]):
                pivotrow = j
        for k in range(i, n+1):
            if k < A.shape[1]: 
                A[i,k], A[pivotrow,k] = A[pivotrow,k], A[i,k]
        for j in range(i+1, n):
            temp = A[j,i] / A[i,i]
            for k in range(n+1):
                if k < A.shape[1]: 
                    A[j,k] = A[j,k] - (temp * A[i,k])

In [113]:
# Test case
A = np.array([[3,  1, 1],
              [-1, 2, 0],
              [4, 5, -2]], dtype=int)

B = np.array([4, 5, -10], dtype=int)

BetterForwardElimination(A, B)
print("Matrix 'A' after Forward Elimination:" + "\n", A)

Matrix 'A' after Forward Elimination:
 [[  4   5 -10]
 [  0   3   2]
 [  0   0  12]]
